# Generated by Django 5.0.6 on 2024-08-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('orig_title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('startYear', models.CharField(blank=True, max_length=20, null=True)),
                ('endYear', models.CharField(blank=True, max_length=50, null=True)),
                ('runtimeMinutes', models.CharField(blank=True, max_length=20, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('birthYear', models.CharField(blank=True, max_length=20, null=True)),
                ('deathYear', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(through='movies.MoviePerson', to='movies.person'),
        ),
    ]
